# set shell
set -g default-shell /usr/bin/fish

# key binding
bind -n C-Tab select-window -n
bind -n M-Tab select-window -p
bind -n C-PageUp select-window -n
bind -n C-PageDown select-window -p

bind -n C-t new-window
bind -n C-q kill-window
bind -n C-s source-file ~/.tmux.conf \; display "Config Reloaded!"
bind -n C-x respawn-pane -k

# alt+1 to alt+9 to switch tabs
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# so that escapes register immediately in vim
##set -sg escape-time 0

# start index at 1
set -g base-index 1

# mouse support
set -g mouse on

# turn on window titles
set -g set-titles on

# set wm window title string
set -g set-titles-string '#W'

# automatically set window title
setw -g automatic-rename on
set -g focus-events on

# fix colors for autocompletion and neovim
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# styling
set -g status-style bg=default
set -g status-style fg=white

set -g status-right ""
set -g status-left ""

set -g status-justify centre

set -g window-status-format "#[fg=yellow]#[fg=black]#[bg=yellow]#I #[bg=brightblack]#[fg=white] #W#[fg=brightblack]#[bg=default] "
set -g window-status-current-format "#[fg=blue]#[fg=black]#[bg=blue]#I #[bg=brightblack]#[fg=white] #W#[fg=brightblack]#[bg=default] "

set-option -g history-limit 5000